
project:
  type: website
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/kanglcn/decorrelation"
  sidebar:
    style: "floating"
    contents:
      - index.ipynb
      - section: API
        contents:
          - API/co.ipynb
          - API/pl.ipynb
          - API/plot.ipynb
          - API/shp.ipynb
      - section: CLI
        contents:
          - CLI/shp.ipynb
          - section: utils
            contents:
              - CLI/utils/logging.ipynb
      - section: Tutorials
        contents:
          - Tutorials/Adaptive_Multilook.ipynb
          - Tutorials/DS_Processing.ipynb
          - Tutorials/Work_With_Dask.ipynb
metadata-files: 
  - sidebar.yml
  - nbdev.yml
